# ============================================================
# Inventaire Ansible — Groupe 3 — Projet Fil Rouge SOC
# Les credentials sont dans group_vars/all/vault.yml (ansible-vault)
# ============================================================

[all:vars]
ansible_user={{ vault_ansible_user }}
ansible_ssh_pass={{ vault_ansible_pass }}
ansible_become=yes
ansible_become_pass={{ vault_ansible_pass }}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# ============================================================
# pfSense
# ============================================================
[pfsense]
G3-pfSense ansible_host=192.168.30.1 ansible_user=admin ansible_python_interpreter=/usr/local/bin/python3.11

# ============================================================
# Serveurs
# ============================================================
[serveurs]
G3-SRV-APP ansible_host=192.168.30.11

# ============================================================
# SOC
# ============================================================
[soc]
G3-SURICATA ansible_host=192.168.30.12
G3-WAZUH    ansible_host=192.168.30.13

# ============================================================
# Postes de travail
# ============================================================
[workstations]
G3-workstation ansible_host=192.168.30.99

# ============================================================
# Groupes logiques
# ============================================================
[linux:children]
serveurs
soc
workstations

[all_g3:children]
serveurs
soc
workstations
